[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aer_datasets"
version = "0.0.1"
authors = [
  { name="Timothy C. Sweeney-Fanelli", email="tim@affects.ai" },
]
description = "An utility package for working with AER Datasets such as ASCERTAIN, DREAMER, MANHOB-HCI, and more"
readme = "README.md"
requires-python = ">=3.11"
license = {file = "LICENSE.txt"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: Free for non-commercial use",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/affectsai/aer-datasets"
Issues = "https://github.com/affectsai/aer-datasets/issues"